version: '3.8'

services:
  mongo:
    image: mongo
    container_name: drone-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/droneDB
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: drone-mongo-express
    restart: unless-stopped
    ports:
      - "8082:8081" # 8081 iç port, 8082 dış port (host'tan erişim için)
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=1234
    depends_on:
      - mongo

volumes:
  mongo-data:
